CREATE TABLE text_stats
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    original_text       CLOB,
    length              INT                                     NOT NULL,
    word_count          INT                                     NOT NULL,
    longest_word        INT                                     NOT NULL,
    average_word_length DOUBLE PRECISION                        NOT NULL,
    most_frequent_word  VARCHAR(255),
    create_at           TIMESTAMP,
    updated_at          TIMESTAMP,
    CONSTRAINT pk_text_stats PRIMARY KEY (id)
);